name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build images
      run: docker-compose -f "docker-compose.yml" build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down