name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Executing Remote SSH command using pub_key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PUB_KEY }}
          port: 22
          script: |
            whoami
            ls -al